on:
  push:
    branches-ignore:
      - 'master'

jobs:
  ci_trigger:
    runs-on: ubuntu-latest
    name: Impersonated CI Trigger
    steps:
      - name: Trigger
        id: trigger
        uses: tripodsan/touch-action@v1.5.4
        with:
          repo-token: ${{ secrets.MY_GITHUB_TOKEN }}
          user: tripod-alt
