on:
  push:
    branches-ignore:
      - 'master'

jobs:
  ci_trigger:
    runs-on: ubuntu-latest
    name: Impersonated CI Trigger
    steps:
      - name: Trigger
        id: trigger
        uses: tripodsan/touch-action@v1.5.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          who-to-greet: 'Robbi the Octocat'
      - name: Get the output time
        run: echo "The time was ${{ steps.trigger.outputs.time }}"
