on:
  push:
    branches-ignore:
      - 'master'

jobs:
  ci_trigger:
    runs-on: ubuntu-latest
    name: Impersonated CI Trigger
    steps:
    - name: Trigger
      id: trigger
      uses: tripodsan/touch-action@v1.2
      with:
        who-to-greet: 'Robbi the Octocat'
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.trigger.outputs.time }}"
