on:
  push:
    branches-ignore:
      - 'master'

jobs:
  ci_trigger:
    runs-on: ubuntu-latest
    name: Comment Semantic Release Status
    steps:
      - name: Comment
        id: comment
        uses: adobe-rnd/semantic-release-comment-action@use-comment-marker
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
